micronaut:
  application:
    name: mnTestcontainersTest
---
netty:
  default:
    allocator:
      max-order: 3
---
datasources:
  default:
    db-type: mysql
r2dbc:
  datasources:
    default:
      db-type: mysql
---
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
---
test-resources:
  containers:
    mysql:
      image-name: mysql:8
